exersize 11: np.diag

In [6]:
import numpy as np 

npa = np.diag(range(5,31,5))

print("npa:", npa)

npa: [[ 5  0  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 25  0]
 [ 0  0  0  0  0 30]]


exersize 12: np.eye

In [9]:
import numpy as np 

npa = np.eye(N=10,M=10, k=0) 
npb = np.eye(N=10)
npc = np.identity(n = 10)
print("npa:", npa)
print("npb:", npb)
print("npb:", npc)

npa: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
npb: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
npb: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 

exersize 13: Missing Exercise

exersize 14: np.sum

In [12]:
import numpy as np
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

print(f'Sum of the elements of array 1: {np.sum(array1)}')
print(f'Sum of the elements of array 2: {np.sum(array2)}')
print(f'Sum of the elements of array 3: {np.sum(array3)}')
print(f'Sum of the elements of array 4: {np.sum(array4)}')
print(f'Sum of the elements of array 5: {np.sum(array5)}')
 

Sum of the elements of array 1: 55
Sum of the elements of array 2: 255.0
Sum of the elements of array 3: 1275
Sum of the elements of array 4: 10056552148.564463
Sum of the elements of array 5: 105


In [17]:
import numpy as np
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

arrays = [array1, array2, array3, array4, array5] 
 
for index, array  in  enumerate(arrays, start = 1):
    print(f'Sum of the elements of array {index}: {array.sum()}') 
    counter+=1

Sum of the elements of array 1: 55
Sum of the elements of array 2: 255.0
Sum of the elements of array 3: 1275
Sum of the elements of array 4: 10056552148.564463
Sum of the elements of array 5: 105


exercise 15: sum of lines and columns

In [30]:
import numpy as np
matrix = np.array(np.random.randint(1,100,15)).reshape(5,3)

print('Total sum of elements: ', matrix.sum())
print('Sum of lines: ', matrix.sum(axis = 1))
print('Sum of columns: ', matrix.sum(axis = 0))

 

Total sum of elements:  855
Sum of lines:  [139 208 175 144 189]
Sum of columns:  [297 200 358]


exersize 16: Min and Max 

In [31]:
import numpy as np
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))

arrays = [array1, array2, array3, array4] 
 
for index, array  in  enumerate(arrays, start = 1):
    print(f'array {index} min: {array.min()}  max: {array.max()}') 
    counter+=1

array 1 min: -1  max: 27
array 2 min: -80  max: 293
array 3 min: -1.1451224335463985  max: 1.5411745593841455
array 4 min: 12  max: 50


exersize 17: matrix calculation

In [37]:
import numpy as np

def info_array(array):
    print(array) 
    print(f'Maximum value of the matrix:  {array.max()}')
    print(f'Maximum value per column:   {array.max(axis=0)}')
    print(f'Maximum value per line:    {array.max(axis=1)}')
    print(f'Minimum value of the matrix:   {array.min()}')
    print(f'Minimum value per column:    {array.min(axis=0)}')
    print(f'Minimum value per line:   {array.min(axis=1)}')

matrix = np.random.randint(-1000,1000,50).reshape(10,5)
info_array(matrix)




[[  62 -445  574  792 -769]
 [ 989 -249  945  897  895]
 [ 328  995 -229  844  -15]
 [-875  721   77  910  871]
 [-284  580   54  491 -839]
 [ 687 -450 -317 -610  339]
 [-476  207  597 -704 -717]
 [ 865 -454  867 -972 -949]
 [-786   92  973 -241   40]
 [-221  977 -350 -405 -510]]
Maximum value of the matrix:  995
Maximum value per column:   [989 995 973 910 895]
Maximum value per line:    [792 989 995 910 580 687 597 867 973 977]
Minimum value of the matrix:   -972
Minimum value per column:    [-875 -454 -350 -972 -949]
Minimum value per line:   [-769 -249 -229 -875 -839 -610 -717 -972 -786 -510]
