Exercise 1: Inspecting a Array NumPy

In [3]:
import numpy  as np
array = np.array([1,2,3,4])
print('Shape:', array.shape) 
print('Size:', array.size)
print('ndim:', array.ndim) 
print('nbytes:', array.nbytes) 
print('dtype:', array.dtype) 

Shape: (4,)
Size: 4
ndim: 1
nbytes: 16
dtype: int32


Exercise 2: Function to check if numpy array and output it's properties

In [22]:
import numpy  as np

def inspect_array(array):
    if type(array) == np.ndarray:
        print('Shape:', array.shape) 
        print('Size:', array.size)
        print('ndim:', array.ndim) 
        print('nbytes:', array.nbytes) 
        print('dtype:', array.dtype) 
        print('dtype:', type(array))
    else:
        print('The inserted object is not a Numpy array.')

inspect_array(np.array([1,2,3])) 
inspect_array([1,2,3]) 

    

Shape: (3,)
Size: 3
ndim: 1
nbytes: 12
dtype: int32
dtype: <class 'numpy.ndarray'>
[1 2 3]
The inserted object is not a Numpy array.


Exercise 3 : creating one-dimension array

In [28]:
import numpy as np

npa = np.array([-1,  4,  7,  9]) 
print("npa:",npa)

npb = np.array(range(1,11,1)) 
print("npb:",npb)

npc = np.array((10,11,12,13,14)) 
print("npc:",npc)

npd = np.array(range(1990,2021,5)) 
print("npd:",npd)

npe = np.array(range(2020,1899,-10)) 
print("npe:",npe)

npf = np.array([100]) 
print("npf:",npf)


npa: [-1  4  7  9]
npb: [ 1  2  3  4  5  6  7  8  9 10]
npc: [10 11 12 13 14]
npd: [1990 1995 2000 2005 2010 2015 2020]
npe: [2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]
npf: [100]


Exercise 4 : 

In [32]:
import numpy as np 

npa = np.ones(shape=(10)) 
npb = np.ones(shape=(4,4)) 
npc = np.ones(shape=(3,2)) 

print("npa:", npa)
print("npb:", npb)
print("npc:", npc)

npa: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
npb: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
npc: [[1. 1.]
 [1. 1.]
 [1. 1.]]
