Exercise 1: Inspecting a Array NumPy

In [3]:
import numpy  as np
array = np.array([1,2,3,4])
print('Shape:', array.shape) 
print('Size:', array.size)
print('ndim:', array.ndim) 
print('nbytes:', array.nbytes) 
print('dtype:', array.dtype) 

Shape: (4,)
Size: 4
ndim: 1
nbytes: 16
dtype: int32


Exercise 2: Function to check if numpy array and output it's properties

In [22]:
import numpy  as np

def inspect_array(array):
    if type(array) == np.ndarray:
        print('Shape:', array.shape) 
        print('Size:', array.size)
        print('ndim:', array.ndim) 
        print('nbytes:', array.nbytes) 
        print('dtype:', array.dtype) 
        print('dtype:', type(array))
    else:
        print('The inserted object is not a Numpy array.')

inspect_array(np.array([1,2,3])) 
inspect_array([1,2,3]) 

    

Shape: (3,)
Size: 3
ndim: 1
nbytes: 12
dtype: int32
dtype: <class 'numpy.ndarray'>
[1 2 3]
The inserted object is not a Numpy array.


Exercise 3 : creating one-dimension array

In [28]:
import numpy as np

npa = np.array([-1,  4,  7,  9]) 
print("npa:",npa)

npb = np.array(range(1,11,1)) 
print("npb:",npb)

npc = np.array((10,11,12,13,14)) 
print("npc:",npc)

npd = np.array(range(1990,2021,5)) 
print("npd:",npd)

npe = np.array(range(2020,1899,-10)) 
print("npe:",npe)

npf = np.array([100]) 
print("npf:",npf)


npa: [-1  4  7  9]
npb: [ 1  2  3  4  5  6  7  8  9 10]
npc: [10 11 12 13 14]
npd: [1990 1995 2000 2005 2010 2015 2020]
npe: [2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]
npf: [100]


Exercise 4 : np.ones

In [32]:
import numpy as np 

npa = np.ones(shape=(10)) 
npb = np.ones(shape=(4,4)) 
npc = np.ones(shape=(3,2)) 

print("npa:", npa)
print("npb:", npb)
print("npc:", npc)

npa: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
npb: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
npc: [[1. 1.]
 [1. 1.]
 [1. 1.]]


Exercise 5: np.zeroes

In [1]:
import numpy as np 

npa = np.zeros(shape=(10)) 
npb = np.zeros(shape=(2,2)) 
npc = np.zeros(shape=(4,6)) 

print("npa:", npa)
print("npb:", npb)
print("npc:", npc)

npa: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
npb: [[0. 0.]
 [0. 0.]]
npc: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Exercise 6: np.arange ang  range

In [16]:
import numpy as np 

npa = np.arange(start=10, stop=50, step=5).reshape(8,1) 
npb = np.arange(start=-50, stop=0, step=5)
npc =  np.array( [range(50, 150, 2)  ]) .reshape(5,10) 


print("npa:", npa)
print("npb:", npb)
print("npc:", npc)


npa: [[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]
npb: [-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]
npc: [[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]


Exercise 7: np.full 

In [20]:
import numpy as np 

npa = np.full(shape=(1,10),fill_value=5, dtype=float) 
npb = np.full(shape=(4,4),fill_value=-5, dtype=float) 
npc = np.full(shape=(3,3),fill_value=3, dtype=int) 
npd = np.full(shape=(10,10),fill_value=50, dtype=int) 

print("npa:", npa)
print("npb:", npb)
print("npc:", npc)
print("npd:", npd)


npa: [[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
npb: [[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]]
npc: [[3 3 3]
 [3 3 3]
 [3 3 3]]
npd: [[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]


Exercise 8: K array and np.isnan()

In [29]:
import numpy as np 

k = np.array([[ np.nan,   1.,  10.,   0.],
       [ np.nan,  np.nan,  np.nan,  np.nan],
       [100.,  50.,  np.nan, -25.],
       [ 30.,  np.nan,  np.nan, 130.]])

print(f'There are {np.isnan(K).sum()} missing data in K.')

There are 8 missing data in K.


In [ ]:
Exercise 9: linspace

In [30]:
import numpy as np 

npa = np.linspace(start=1,  stop=21 , num=5 )

print("npa:", npa)
 

npa: [ 1.  6. 11. 16. 21.]


Exercise 10: logspace

In [34]:
import numpy as np 

npa = np.logspace(start=1,  stop=51 , num=10 ).reshape((1,1))

print("npa:", npa)
 

npa: [[1.00000000e+01]
 [3.59381366e+06]
 [1.29154967e+12]
 [4.64158883e+17]
 [1.66810054e+23]
 [5.99484250e+28]
 [2.15443469e+34]
 [7.74263683e+39]
 [2.78255940e+45]
 [1.00000000e+51]]
