exersize 11: np.diag

In [6]:
import numpy as np 

npa = np.diag(range(5,31,5))

print("npa:", npa)

npa: [[ 5  0  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 25  0]
 [ 0  0  0  0  0 30]]


exersize 12: np.eye

In [9]:
import numpy as np 

npa = np.eye(N=10,M=10, k=0) 
npb = np.eye(N=10)
npc = np.identity(n = 10)
print("npa:", npa)
print("npb:", npb)
print("npb:", npc)

npa: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
npb: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
npb: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 

exersize 13: Missing Exercise

exersize 14: np.sum

In [12]:
import numpy as np
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

print(f'Sum of the elements of array 1: {np.sum(array1)}')
print(f'Sum of the elements of array 2: {np.sum(array2)}')
print(f'Sum of the elements of array 3: {np.sum(array3)}')
print(f'Sum of the elements of array 4: {np.sum(array4)}')
print(f'Sum of the elements of array 5: {np.sum(array5)}')
 

Sum of the elements of array 1: 55
Sum of the elements of array 2: 255.0
Sum of the elements of array 3: 1275
Sum of the elements of array 4: 10056552148.564463
Sum of the elements of array 5: 105


In [17]:
import numpy as np
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

arrays = [array1, array2, array3, array4, array5] 
 
for index, array  in  enumerate(arrays, start = 1):
    print(f'Sum of the elements of array {index}: {array.sum()}') 
    counter+=1

Sum of the elements of array 1: 55
Sum of the elements of array 2: 255.0
Sum of the elements of array 3: 1275
Sum of the elements of array 4: 10056552148.564463
Sum of the elements of array 5: 105


exercise 15: sum of lines and columns

In [29]:
import numpy as np
matrix = np.array(np.random.randint(1,100,15)).reshape(5,3)

print(f'Sum of the elements of array: {matrix.sum()}')

(cols,lines ) =  matrix.shape 

for col in range( 0, cols-1):
    print(f'Sum of the elements of col {col} : {matrix[col].sum()}')

for line in range( 0, lines-1):
    print(f'Sum of the elements of lines {line} : {matrix[line].sum()}')


matrix.row

Sum of the elements of array: 539
Sum of the elements of col 0 : 176
Sum of the elements of col 1 : 140
Sum of the elements of col 2 : 38
Sum of the elements of col 3 : 77
Sum of the elements of lines 0 : 176
Sum of the elements of lines 1 : 140


AttributeError: 'numpy.ndarray' object has no attribute 'row'